### ISSUE TITLE
player token doesn't match token on board

### ISSUE THREAD

**Issue by asalduur** [Clue-Group-Project/Clue-App#31]
we have a function now where game randomizes player token color (can be green, blue, red, or yellow so far).

however, the token moving on board stays green, and while this worked with how the game was set up previously, it doesn't work now.

![image](https://user-images.githubusercontent.com/69156982/123437530-c2d12400-d59d-11eb-856f-e0fb2f6ad432.png)

**Comment by michellegaletti** [comment]
I will have to look at the code and see how to fix this, thanks for noting @asalduur

**Comment by asalduur** [comment]
fixed in [this commit](https://github.com/Clue-Group-Project/Clue-App/commit/46fdaaa0bf8b48119d10ad089839f17e639a702e)
